const Music = require('../index')
  ; (async () => {
    let data = await Music.qq.search('浮夸')
    let detail = await Music.qq.song(data.list[0].id)
    console.log(data.list.length, detail)
    data = await Music.netease.search('浮夸')
    detail = await Music.netease.song(data.list[0].id)
    console.log(data.list.length, detail)
    data = await Music.kuwo.search('浮夸')
    detail = await Music.kuwo.song(data.list[0].id)
    console.log(data.list.length, detail)
    data = await Music.kugou.search('浮夸')
    detail = await Music.kugou.song(data.list[0].id)
    console.log(data.list.length, detail)
  })()